In [7]:
from torch_geometric.datasets import TUDataset
from torch_geometric.loader import DataLoader
from sklearn.model_selection import train_test_split
import wandb 
import os 
from dotenv import load_dotenv
from torch import nn 
import torch


In [8]:

inp_name = input('Enter the dataset to be downloaded: ')

imdb_b = os.getenv('imdb_b')
reddit_b = os.getenv('reddit_b')
collab = os.getenv('collab')
mutag = os.getenv('mutag')
proteins = os.getenv('proteins')

if inp_name == 'imdb_b':
    dataset = TUDataset(
        root=imdb_b, name='IMDB-BINARY', use_node_attr=True)
elif inp_name == 'reddit_b':
    dataset = TUDataset(
        root=reddit_b, name='REDDIT-BINARY', use_node_attr=True)
elif inp_name == 'collab':
    dataset = TUDataset(root=collab, name='COLLAB', use_node_attr=True)
elif inp_name == 'mutag':
    dataset = TUDataset(root=mutag, name='MUTAG', use_node_attr=True)
elif inp_name == 'proteins':
    dataset = TUDataset(root=proteins, name='PROTEINS', use_node_attr=True)


In [9]:
train_ratio = 0.75
validation_ratio = 0.10
test_ratio = 0.15

train_set,test_set = train_test_split(dataset,test_size=1 - train_ratio)

val_set,test_set= train_test_split(test_set, test_size=test_ratio/(test_ratio + validation_ratio))

In [10]:
import torch
from torch import nn 

In [11]:
num_layers=3
curvatures=[nn.Parameter(torch.tensor([1.]))for _ in range(num_layers-1)]

In [ ]:
curvatures

[Parameter containing:
 tensor([1.], requires_grad=True),
 Parameter containing:
 tensor([1.], requires_grad=True)]

In [25]:
from torch_geometric.utils import to_dense_adj,to_torch_sparse_tensor,dense_to_sparse,to_torch_coo_tensor
graph=train_set[0]
x,adj=graph.x,to_dense_adj(graph.edge_index)

In [26]:
sparse_adj=dense_to_sparse(adj)

In [27]:
adj

tensor([[[0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
         [0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0.],
         [0., 0., 0., 0.,

In [28]:
sparse_adj

(tensor([[ 0,  0,  1,  1,  2,  2,  2,  3,  3,  4,  4,  5,  5,  5,  6,  6,  6,  7,
           7,  8,  8,  9,  9,  9, 10, 10, 11, 11, 12, 12, 12, 13, 14, 15],
         [ 1,  5,  0,  2,  1,  3, 15,  2,  4,  3,  5,  0,  4,  6,  5,  7, 11,  6,
           8,  7,  9,  8, 10, 12,  9, 11,  6, 10,  9, 13, 14, 12, 12,  2]]),
 tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]))

In [29]:
sparse=to_torch_coo_tensor(graph.edge_index)

In [30]:
sparse.indices()

tensor([[ 0,  0,  1,  1,  2,  2,  2,  3,  3,  4,  4,  5,  5,  5,  6,  6,  6,  7,
          7,  8,  8,  9,  9,  9, 10, 10, 11, 11, 12, 12, 12, 13, 14, 15],
        [ 1,  5,  0,  2,  1,  3, 15,  2,  4,  3,  5,  0,  4,  6,  5,  7, 11,  6,
          8,  7,  9,  8, 10, 12,  9, 11,  6, 10,  9, 13, 14, 12, 12,  2]])